#!/usr/bin/env bash
set -euo pipefail
# Script to initialize tmuxinator with worktree project
echo "TMUX project script"
if [[ $TERM =~ ^screen.* ]]; then
	if [[ -z "$*" ]]; then
		fd --type d | fzf-tmux -p | xargs tmuxinator start PRJ
	else
		if [[ "$1" == "." ]]; then
			tmuxinator start PRJ "$(pwd)"
		else
			tmuxinator start PRJ "$1"
		fi
	fi
else
	exec tmux
fi
